export const ROUTES = {
  PUBLIC_HOME: "PublicHome",
  LOGIN: "Login",
  REGISTER_COMPANY: "RegisterCompany",

  OPERATOR_TABS: "OperatorTabs",
  OPERATOR_DASHBOARD: "OperatorDashboard",
  OPERATOR_SHIPMENTS: "OperatorShipments",
  NEW_SHIPMENT: "NewShipment",
  OPERATOR_TRACKING: "OperatorTracking",
  OPERATOR_COURIERS: "OperatorCouriers",
  OPERATOR_REPORTS: "OperatorReports",
  COMPANY_PROFILE: "CompanyProfile",
  USER_PROFILE_EDIT: "UserProfileEdit",

  SHIPMENT_DETAILS: "ShipmentDetails",

  COURIER_DELIVERIES: "CourierDeliveries",
  COURIER_DELIVERY_DETAILS: "CourierDeliveryDetails",

  UNSUPPORTED_ROLE: "UnsupportedRole",
};

export const PUBLIC_ROUTES = [
  ROUTES.PUBLIC_HOME,
  ROUTES.LOGIN,
  ROUTES.REGISTER_COMPANY,
];

export const OPERATOR_ROUTES = [
  ROUTES.OPERATOR_DASHBOARD,
  ROUTES.OPERATOR_SHIPMENTS,
  ROUTES.NEW_SHIPMENT,
  ROUTES.OPERATOR_TRACKING,
  ROUTES.OPERATOR_COURIERS,
  ROUTES.OPERATOR_REPORTS,
  ROUTES.COMPANY_PROFILE,
  ROUTES.USER_PROFILE_EDIT,
  ROUTES.SHIPMENT_DETAILS,
];

export const COURIER_ROUTES = [
  ROUTES.COURIER_DELIVERIES,
  ROUTES.COURIER_DELIVERY_DETAILS,
];

export const SHARED_PRIVATE_ROUTES = [
  ROUTES.SHIPMENT_DETAILS,
  ROUTES.UNSUPPORTED_ROLE,
];