export const DELIVERY_STATUS = {
  CREATED: "CREATED",
  POSTED: "POSTED",
  IN_TRANSIT: "IN_TRANSIT",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  CANCELED: "CANCELED",
};

export const STATUS_LABELS = {
  CREATED: "Criado",
  POSTED: "Postado",
  IN_TRANSIT: "Em trânsito",
  OUT_FOR_DELIVERY: "Saiu para entrega",
  DELIVERED: "Entregue",
  CANCELED: "Cancelado",
};

export const FINAL_STATUSES = [
  DELIVERY_STATUS.DELIVERED,
  DELIVERY_STATUS.CANCELED,
];

export const ACTIVE_STATUSES = [
  DELIVERY_STATUS.CREATED,
  DELIVERY_STATUS.POSTED,
  DELIVERY_STATUS.IN_TRANSIT,
  DELIVERY_STATUS.OUT_FOR_DELIVERY,
];

export const OPERATOR_ALLOWED_TRANSITIONS = {
  [DELIVERY_STATUS.CREATED]: [
    DELIVERY_STATUS.POSTED,
    DELIVERY_STATUS.CANCELED,
  ],
  [DELIVERY_STATUS.POSTED]: [
    DELIVERY_STATUS.IN_TRANSIT,
    DELIVERY_STATUS.CANCELED,
  ],
  [DELIVERY_STATUS.IN_TRANSIT]: [
    DELIVERY_STATUS.CANCELED,
  ],
  [DELIVERY_STATUS.OUT_FOR_DELIVERY]: [],
  [DELIVERY_STATUS.DELIVERED]: [],
  [DELIVERY_STATUS.CANCELED]: [],
};

export const COURIER_ALLOWED_TRANSITIONS = {
  [DELIVERY_STATUS.CREATED]: [],
  [DELIVERY_STATUS.POSTED]: [],
  [DELIVERY_STATUS.IN_TRANSIT]: [
    DELIVERY_STATUS.OUT_FOR_DELIVERY,
  ],
  [DELIVERY_STATUS.OUT_FOR_DELIVERY]: [
    DELIVERY_STATUS.DELIVERED,
  ],
  [DELIVERY_STATUS.DELIVERED]: [],
  [DELIVERY_STATUS.CANCELED]: [],
};

export const EVENT_TYPE_BY_STATUS = {
  [DELIVERY_STATUS.CREATED]: "DELIVERY_CREATED",
  [DELIVERY_STATUS.POSTED]: "DELIVERY_POSTED",
  [DELIVERY_STATUS.IN_TRANSIT]: "DELIVERY_IN_TRANSIT",
  [DELIVERY_STATUS.OUT_FOR_DELIVERY]: "DELIVERY_OUT_FOR_DELIVERY",
  [DELIVERY_STATUS.DELIVERED]: "DELIVERY_DELIVERED",
  [DELIVERY_STATUS.CANCELED]: "DELIVERY_CANCELED",
};